name: test
channels:
  - conda-forge
  - defaults

dependencies:
    # Base depends
  - python >=3.7
  - pip

  # Package dependencies
  - setuptools
  - beautifulsoup4
  - bioformats_jar
  - colorama
  - fastcluster
  - interpolation
  - joblib
  - jpype1
  - matplotlib-base
  - numba
  - numpy
  - ome-types
  - opencv
  - pandas
  - Pillow
  - pyvips
  - scikit-image
  - scikit-learn
  - scipy
  - Shapely
  - SimpleITK
  - tqdm
  - weightedstats
  - wheel
  - lxml
  - colour-science
  - libvips  >=8.11,<8.12
    # Testing
  - pytest
  - pytest-cov
  - codecov


    # Pip-only installs
  #- pip:
  #  - codecov