name: Pull Request Docs Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: MathOnco/valis@main
      with:
        docs-folder: "docs/"
        build-command: "sphinx-build -b html . build"
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/build/html/
